export interface CollaboratorCompany {
  id: number;
  nome: string;
}

export interface CollaboratorProps {
  id?: number;
  isFreelancer?: boolean;
  codigo?: string | null;
  nome?: string | null;
  cpf?: string | null;
  cargo?: string | null;
  email?: string | null;
  telefone?: string | null;
  endereco?: string | null;
  cidade?: string | null;
  uf?: string | null;
  dataAdmissao?: string | null;
  status?: string;
  companyId?: number;
  company?: CollaboratorCompany | null;
  userId?: number;
  razaoSocial?: string;
  tipoContrato?: string;
  regional?: string;
  funcao?: string;
  foto?: string;
  firstName?: string;
  lastName?: string;
  birthDate?: string;
  rg?: string;
  orgaoEmissor?: string;
  naturalidade?: string;
  sexo?: string;
  cnpj?: string;
  tituloEleitor?: string;
  rgArquivo?: string;
  carteiraArquivo?: string;
  habilitacaoArquivo?: string;
  nr10Arquivo?: string;
  nr35Arquivo?: string;
  asoArquivo?: string;
  epiArquivo?: string;
  ordemServicoArquivo?: string;
  contratoArquivo?: string;
  cnh?: string;
  cnhValidade?: string;
  pis?: string;
  phone?: string;
  whatsapp?: string;
  contatoEmergenciaNome?: string;
  contatoEmergenciaTelefone?: string;
  contatoEmergenciaParentesco?: string;
  cep?: string;
  banco?: string;
  agencia?: string;
  conta?: string;
  tipoConta?: string;
  pix?: string;
  titular?: string;
  trainings?: string;
  dataAso?: string;
  dataNr06?: string;
  dataNr35?: string;
  dataNr10?: string;
  dataNr75?: string;
  dataNr01?: string;
  dataIntegracao?: string;
  dataListaFerramental?: string;
  cracha?: string;
  dataHs?: string;
  dataLtw?: string;
  dataCadastroNokia?: string;
  dataCadastroEricsson?: string;
  dataCadastroTelebit?: string;
  vencimentoAso?: string;
  vencimentoNr35?: string;
  vencimentoNr10?: string;
  uniforms?: string;
  epis?: string;
  bio?: string;
  hourlyRate?: number;
  skills?: string;
  portfolio?: string;
  experienceLevel?: string;
  availability?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export class Collaborator {
  id?: number;
  isFreelancer: boolean;
  codigo?: string | null;
  nome?: string | null;
  cpf?: string | null;
  cargo?: string | null;
  email?: string | null;
  telefone?: string | null;
  endereco?: string | null;
  cidade?: string | null;
  uf?: string | null;
  dataAdmissao?: string | null;
  status: string;
  companyId?: number;
  company?: CollaboratorCompany | null;
  userId?: number;
  razaoSocial?: string;
  tipoContrato?: string;
  regional?: string;
  funcao?: string;
  foto?: string;
  firstName?: string;
  lastName?: string;
  birthDate?: string;
  rg?: string;
  orgaoEmissor?: string;
  naturalidade?: string;
  sexo?: string;
  cnpj?: string;
  tituloEleitor?: string;
  rgArquivo?: string;
  carteiraArquivo?: string;
  habilitacaoArquivo?: string;
  nr10Arquivo?: string;
  nr35Arquivo?: string;
  asoArquivo?: string;
  epiArquivo?: string;
  ordemServicoArquivo?: string;
  contratoArquivo?: string;
  cnh?: string;
  cnhValidade?: string;
  pis?: string;
  phone?: string;
  whatsapp?: string;
  contatoEmergenciaNome?: string;
  contatoEmergenciaTelefone?: string;
  contatoEmergenciaParentesco?: string;
  cep?: string;
  banco?: string;
  agencia?: string;
  conta?: string;
  tipoConta?: string;
  pix?: string;
  titular?: string;
  trainings?: string;
  dataAso?: string;
  dataNr06?: string;
  dataNr35?: string;
  dataNr10?: string;
  dataNr75?: string;
  dataNr01?: string;
  dataIntegracao?: string;
  dataListaFerramental?: string;
  cracha?: string;
  dataHs?: string;
  dataLtw?: string;
  dataCadastroNokia?: string;
  dataCadastroEricsson?: string;
  dataCadastroTelebit?: string;
  vencimentoAso?: string;
  vencimentoNr35?: string;
  vencimentoNr10?: string;
  uniforms?: string;
  epis?: string;
  bio?: string;
  hourlyRate?: number;
  skills?: string;
  portfolio?: string;
  experienceLevel?: string;
  availability?: string;
  createdAt?: Date;
  updatedAt?: Date;

  constructor(props: CollaboratorProps) {
    Object.assign(this, { status: 'ativo', isFreelancer: false, ...props });
  }
}
