export interface CollaboratorCompany {
  id: number;
  nome: string;
}

export interface CollaboratorProps {
  id?: number;
  isFreelancer?: boolean;
  codigo?: string | null;
  nome?: string | null;
  cpf?: string | null;
  cargo?: string | null;
  email?: string | null;
  telefone?: string | null;
  endereco?: string | null;
  cidade?: string | null;
  uf?: string | null;
  dataAdmissao?: string | null;
  status?: string;
  companyId?: number;
  company?: CollaboratorCompany | null;
  userId?: number;
  razaoSocial?: string;
  tipoContrato?: string;
  regional?: string;
  funcao?: string;
  foto?: string;
  firstName?: string;
  lastName?: string;
  birthDate?: string;
  rg?: string;
  orgaoEmissor?: string;
  naturalidade?: string;
  sexo?: string;
  cnpj?: string;
  tituloEleitor?: string;
  rgArquivo?: string;
  carteiraArquivo?: string;
  habilitacaoArquivo?: string;
  nr10Arquivo?: string;
  nr35Arquivo?: string;
  asoArquivo?: string;
  epiArquivo?: string;
  ordemServicoArquivo?: string;
  contratoArquivo?: string;
  cnh?: string;
  cnhValidade?: string;
  pis?: string;
  phone?: string;
  whatsapp?: string;
  contatoEmergenciaNome?: string;
  contatoEmergenciaTelefone?: string;
  contatoEmergenciaParentesco?: string;
  cep?: string;
  banco?: string;
  agencia?: string;
  conta?: string;
  tipoConta?: string;
  pix?: string;
  titular?: string;
  trainings?: string;
  dataAso?: string;
  dataNr06?: string;
  dataNr35?: string;
  dataNr10?: string;
  dataNr75?: string;
  dataNr01?: string;
  dataIntegracao?: string;
  dataListaFerramental?: string;
  cracha?: string;
  dataHs?: string;
  dataLtw?: string;
  dataCadastroNokia?: string;
  dataCadastroEricsson?: string;
  dataCadastroTelebit?: string;
  vencimentoAso?: string;
  vencimentoNr35?: string;
  vencimentoNr10?: string;
  uniforms?: string;
  epis?: string;
  bio?: string;
  hourlyRate?: number;
  skills?: string;
  portfolio?: string;
  experienceLevel?: string;
  availability?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export class Collaborator {
  id?: number;
  isFreelancer: boolean;
  codigo?: string | null;
  nome?: string | null;
  cpf?: string | null;
  cargo?: string | null;
  email?: string | null;
  telefone?: string | null;
  endereco?: string | null;
  cidade?: string | null;
  uf?: string | null;
  dataAdmissao?: string | null;
  status: string;
  companyId?: number;
  company?: CollaboratorCompany | null;
  userId?: number;
  razaoSocial?: string;
  tipoContrato?: string;
  regional?: string;
  funcao?: string;
  foto?: string;
  firstName?: string;
  lastName?: string;
  birthDate?: string;
  rg?: string;
  orgaoEmissor?: string;
  naturalidade?: string;
  sexo?: string;
  cnpj?: string;
  tituloEleitor?: string;
  rgArquivo?: string;
  carteiraArquivo?: string;
  habilitacaoArquivo?: string;
  nr10Arquivo?: string;
  nr35Arquivo?: string;
  asoArquivo?: string;
  epiArquivo?: string;
  ordemServicoArquivo?: string;
  contratoArquivo?: string;
  cnh?: string;
  cnhValidade?: string;
  pis?: string;
  phone?: string;
  whatsapp?: string;
  contatoEmergenciaNome?: string;
  contatoEmergenciaTelefone?: string;
  contatoEmergenciaParentesco?: string;
  cep?: string;
  banco?: string;
  agencia?: string;
  conta?: string;
  tipoConta?: string;
  pix?: string;
  titular?: string;
  trainings?: string;
  dataAso?: string;
  dataNr06?: string;
  dataNr35?: string;
  dataNr10?: string;
  dataNr75?: string;
  dataNr01?: string;
  dataIntegracao?: string;
  dataListaFerramental?: string;
  cracha?: string;
  dataHs?: string;
  dataLtw?: string;
  dataCadastroNokia?: string;
  dataCadastroEricsson?: string;
  dataCadastroTelebit?: string;
  vencimentoAso?: string;
  vencimentoNr35?: string;
  vencimentoNr10?: string;
  uniforms?: string;
  epis?: string;
  bio?: string;
  hourlyRate?: number;
  skills?: string;
  portfolio?: string;
  experienceLevel?: string;
  availability?: string;
  createdAt?: Date;
  updatedAt?: Date;

  constructor(props: CollaboratorProps) {
    this.id = props.id;
    this.isFreelancer = props.isFreelancer ?? false;
    this.codigo = props.codigo;
    this.nome = props.nome;
    this.cpf = props.cpf;
    this.cargo = props.cargo;
    this.email = props.email;
    this.telefone = props.telefone;
    this.endereco = props.endereco;
    this.cidade = props.cidade;
    this.uf = props.uf;
    this.dataAdmissao = props.dataAdmissao;
    this.status = props.status ?? 'ativo';
    this.companyId = props.companyId;
    this.company = props.company;
    this.userId = props.userId;
    this.razaoSocial = props.razaoSocial;
    this.tipoContrato = props.tipoContrato;
    this.regional = props.regional;
    this.funcao = props.funcao;
    this.foto = props.foto;
    this.firstName = props.firstName;
    this.lastName = props.lastName;
    this.birthDate = props.birthDate;
    this.rg = props.rg;
    this.orgaoEmissor = props.orgaoEmissor;
    this.naturalidade = props.naturalidade;
    this.sexo = props.sexo;
    this.cnpj = props.cnpj;
    this.tituloEleitor = props.tituloEleitor;
    this.rgArquivo = props.rgArquivo;
    this.carteiraArquivo = props.carteiraArquivo;
    this.habilitacaoArquivo = props.habilitacaoArquivo;
    this.nr10Arquivo = props.nr10Arquivo;
    this.nr35Arquivo = props.nr35Arquivo;
    this.asoArquivo = props.asoArquivo;
    this.epiArquivo = props.epiArquivo;
    this.ordemServicoArquivo = props.ordemServicoArquivo;
    this.contratoArquivo = props.contratoArquivo;
    this.cnh = props.cnh;
    this.cnhValidade = props.cnhValidade;
    this.pis = props.pis;
    this.phone = props.phone;
    this.whatsapp = props.whatsapp;
    this.contatoEmergenciaNome = props.contatoEmergenciaNome;
    this.contatoEmergenciaTelefone = props.contatoEmergenciaTelefone;
    this.contatoEmergenciaParentesco = props.contatoEmergenciaParentesco;
    this.cep = props.cep;
    this.banco = props.banco;
    this.agencia = props.agencia;
    this.conta = props.conta;
    this.tipoConta = props.tipoConta;
    this.pix = props.pix;
    this.titular = props.titular;
    this.trainings = props.trainings;
    this.dataAso = props.dataAso;
    this.dataNr06 = props.dataNr06;
    this.dataNr35 = props.dataNr35;
    this.dataNr10 = props.dataNr10;
    this.dataNr75 = props.dataNr75;
    this.dataNr01 = props.dataNr01;
    this.dataIntegracao = props.dataIntegracao;
    this.dataListaFerramental = props.dataListaFerramental;
    this.cracha = props.cracha;
    this.dataHs = props.dataHs;
    this.dataLtw = props.dataLtw;
    this.dataCadastroNokia = props.dataCadastroNokia;
    this.dataCadastroEricsson = props.dataCadastroEricsson;
    this.dataCadastroTelebit = props.dataCadastroTelebit;
    this.vencimentoAso = props.vencimentoAso;
    this.vencimentoNr35 = props.vencimentoNr35;
    this.vencimentoNr10 = props.vencimentoNr10;
    this.uniforms = props.uniforms;
    this.epis = props.epis;
    this.bio = props.bio;
    this.hourlyRate = props.hourlyRate;
    this.skills = props.skills;
    this.portfolio = props.portfolio;
    this.experienceLevel = props.experienceLevel;
    this.availability = props.availability;
    this.createdAt = props.createdAt;
    this.updatedAt = props.updatedAt;
  }
}
