import { z } from 'zod';

export const createCollaboratorSchema = z.object({
  nome: z.string().min(1, 'Nome é obrigatório.'),
  cpf: z.string().optional(),
  cargo: z.string().optional(),
  email: z.string().email('Email inválido.').optional(),
  telefone: z.string().optional(),
  endereco: z.string().optional(),
  cidade: z.string().optional(),
  uf: z.string().optional(),
  dataAdmissao: z.string().optional(),
  status: z.enum(['ativo', 'inativo']).optional(),
  companyId: z.number().int().positive('Informe a empresa.'),
  isFreelancer: z.boolean().optional(),
  razaoSocial: z.string().optional(),
  tipoContrato: z.string().optional(),
  regional: z.string().optional(),
  funcao: z.string().optional(),
  birthDate: z.string().optional(),
  rg: z.string().optional(),
  orgaoEmissor: z.string().optional(),
  naturalidade: z.string().optional(),
  sexo: z.string().optional(),
  cnpj: z.string().optional(),
  tituloEleitor: z.string().optional(),
  cnh: z.string().optional(),
  cnhValidade: z.string().optional(),
  pis: z.string().optional(),
  whatsapp: z.string().optional(),
  contatoEmergenciaNome: z.string().optional(),
  contatoEmergenciaTelefone: z.string().optional(),
  contatoEmergenciaParentesco: z.string().optional(),
  cep: z.string().optional(),
  banco: z.string().optional(),
  agencia: z.string().optional(),
  conta: z.string().optional(),
  tipoConta: z.string().optional(),
  pix: z.string().optional(),
  titular: z.string().optional(),
  trainings: z.string().optional(),
  dataAso: z.string().optional(),
  dataNr06: z.string().optional(),
  dataNr35: z.string().optional(),
  dataNr10: z.string().optional(),
  dataNr75: z.string().optional(),
  dataNr01: z.string().optional(),
  dataIntegracao: z.string().optional(),
  dataListaFerramental: z.string().optional(),
  cracha: z.string().optional(),
  dataHs: z.string().optional(),
  dataLtw: z.string().optional(),
  dataCadastroNokia: z.string().optional(),
  dataCadastroEricsson: z.string().optional(),
  dataCadastroTelebit: z.string().optional(),
  vencimentoAso: z.string().optional(),
  vencimentoNr35: z.string().optional(),
  vencimentoNr10: z.string().optional(),
  uniforms: z.string().optional(),
  epis: z.string().optional(),
  bio: z.string().optional(),
  hourlyRate: z.number().min(0).optional(),
  skills: z.string().optional(),
  portfolio: z.string().optional(),
  experienceLevel: z.enum(['junior', 'mid', 'senior', 'lead']).optional(),
  availability: z.enum(['available', 'busy', 'unavailable']).optional(),
});

export const updateCollaboratorSchema = z
  .object({
    nome: z.string().min(1, 'Nome é obrigatório.').optional(),
    cpf: z.string().optional(),
    cargo: z.string().optional(),
    email: z.string().email('Email inválido.').optional(),
    telefone: z.string().optional(),
    endereco: z.string().optional(),
    cidade: z.string().optional(),
    uf: z.string().optional(),
    dataAdmissao: z.string().optional(),
    status: z.enum(['ativo', 'inativo']).optional(),
    companyId: z.number().int().positive().optional(),
    isFreelancer: z.boolean().optional(),
    razaoSocial: z.string().optional(),
    tipoContrato: z.string().optional(),
    regional: z.string().optional(),
    funcao: z.string().optional(),
    birthDate: z.string().optional(),
    rg: z.string().optional(),
    orgaoEmissor: z.string().optional(),
    naturalidade: z.string().optional(),
    sexo: z.string().optional(),
    cnpj: z.string().optional(),
    tituloEleitor: z.string().optional(),
    cnh: z.string().optional(),
    cnhValidade: z.string().optional(),
    pis: z.string().optional(),
    whatsapp: z.string().optional(),
    contatoEmergenciaNome: z.string().optional(),
    contatoEmergenciaTelefone: z.string().optional(),
    contatoEmergenciaParentesco: z.string().optional(),
    cep: z.string().optional(),
    banco: z.string().optional(),
    agencia: z.string().optional(),
    conta: z.string().optional(),
    tipoConta: z.string().optional(),
    pix: z.string().optional(),
    titular: z.string().optional(),
    trainings: z.string().optional(),
    dataAso: z.string().optional(),
    dataNr06: z.string().optional(),
    dataNr35: z.string().optional(),
    dataNr10: z.string().optional(),
    dataNr75: z.string().optional(),
    dataNr01: z.string().optional(),
    dataIntegracao: z.string().optional(),
    dataListaFerramental: z.string().optional(),
    cracha: z.string().optional(),
    dataHs: z.string().optional(),
    dataLtw: z.string().optional(),
    dataCadastroNokia: z.string().optional(),
    dataCadastroEricsson: z.string().optional(),
    dataCadastroTelebit: z.string().optional(),
    vencimentoAso: z.string().optional(),
    vencimentoNr35: z.string().optional(),
    vencimentoNr10: z.string().optional(),
    uniforms: z.string().optional(),
    epis: z.string().optional(),
    bio: z.string().optional(),
    hourlyRate: z.number().min(0).optional(),
    skills: z.string().optional(),
    portfolio: z.string().optional(),
    experienceLevel: z.enum(['junior', 'mid', 'senior', 'lead']).optional(),
    availability: z.enum(['available', 'busy', 'unavailable']).optional(),
  })
  .refine((data) => Object.keys(data).length > 0, {
    message: 'Informe ao menos um campo para atualizar.',
  });

export type CreateCollaboratorInput = z.infer<typeof createCollaboratorSchema>;
export type UpdateCollaboratorInput = z.infer<typeof updateCollaboratorSchema>;
