export const ROLE_TYPES = [
  'master',
  'admin',
  'supervisor',
  'coordenador',
  'analista',
  'technician',
  'user',
] as const;

export const ALL_ROLE_MODULES = [
  { value: '/tasks', label: 'Tarefas' },
  { value: '/service-orders', label: 'Ordens de Serviço' },
  { value: '/collaborators', label: 'Colaboradores' },
  { value: '/stations', label: 'Estações' },
  { value: '/radio-links', label: 'Enlaces de Rádio' },
  { value: '/projects', label: 'Projetos' },
  { value: '/clients', label: 'Clientes' },
  { value: '/pdca', label: 'PDCA' },
  { value: '/users', label: 'Usuários' },
  { value: '/attachments', label: 'Anexos' },
  { value: '/comments', label: 'Comentários' },
  { value: '/lpus', label: 'LPU' },
  { value: '/teams', label: 'Equipes' },
  { value: '/settings', label: 'Configurações' },
  { value: '/schedule', label: 'Agenda' },
  { value: '/ms-project', label: 'Cronograma' },
  { value: '/finance', label: 'Finanças' },
  { value: '/companies', label: 'Empresas' },
  { value: '/jobs', label: 'Jobs' },
];

export const DEFAULT_ROLE_MODULES: Record<string, string[]> = {
  admin: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/users',
    '/attachments',
    '/comments',
    '/lpus',
    '/teams',
    '/settings',
    '/jobs',
  ],
  supervisor: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/attachments',
    '/comments',
    '/lpus',
    '/teams',
    '/settings',
    '/jobs',
  ],
  coordenador: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/attachments',
    '/comments',
    '/lpus',
    '/teams',
    '/settings',
    '/jobs',
  ],
  analista: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/lpus',
    '/attachments',
    '/comments',
    '/settings',
    '/jobs',
  ],
  technician: [
    '/tasks',
    '/service-orders',
    '/stations',
    '/radio-links',
    '/projects',
    '/pdca',
    '/attachments',
    '/comments',
    '/settings',
    '/jobs',
  ],
  user: [
    '/tasks',
    '/service-orders',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/attachments',
    '/comments',
    '/settings',
    '/jobs',
  ],
  master: [],
};

export const DEFAULT_USER_ALLOWED_PREFIXES = DEFAULT_ROLE_MODULES.user;

export const roleModulesKey = (role: string): string => `role_modules_${role}`;
