export const ROLE_TYPES = [
  'master',
  'admin',
  'supervisor',
  'coordenador',
  'analista',
  'technician',
  'user',
] as const

export type RoleType = (typeof ROLE_TYPES)[number]

export const roleOptions: { value: RoleType; label: string }[] = [
  { value: 'master', label: 'Master' },
  { value: 'admin', label: 'Admin' },
  { value: 'supervisor', label: 'Supervisor' },
  { value: 'coordenador', label: 'Coordenador' },
  { value: 'analista', label: 'Analista' },
  { value: 'technician', label: 'Técnico' },
  { value: 'user', label: 'Usuário' },
]

export const roleLabels: Record<string, string> = roleOptions.reduce(
  (acc, o) => ({ ...acc, [o.value]: o.label }),
  {},
)

export const ALL_ROLE_MODULES: { value: string; label: string }[] = [
  { value: '/tasks', label: 'Tarefas' },
  { value: '/service-orders', label: 'Ordens de Serviço' },
  { value: '/collaborators', label: 'Colaboradores' },
  { value: '/stations', label: 'Estações' },
  { value: '/radio-links', label: 'Enlaces de Rádio' },
  { value: '/projects', label: 'Projetos' },
  { value: '/clients', label: 'Clientes' },
  { value: '/pdca', label: 'PDCA' },
  { value: '/users', label: 'Usuários' },
  { value: '/attachments', label: 'Anexos' },
  { value: '/comments', label: 'Comentários' },
  { value: '/lpus', label: 'LPU' },
  { value: '/teams', label: 'Equipes' },
  { value: '/settings', label: 'Configurações' },
  { value: '/schedule', label: 'Agenda' },
  { value: '/ms-project', label: 'Cronograma' },
  { value: '/finance', label: 'Finanças' },
  { value: '/companies', label: 'Empresas' },
]

export const DEFAULT_ROLE_MODULES: Record<string, string[]> = {
  admin: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/users',
    '/attachments',
    '/comments',
    '/lpus',
    '/teams',
    '/settings',
  ],
  supervisor: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/attachments',
    '/comments',
    '/lpus',
    '/teams',
    '/settings',
  ],
  coordenador: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/attachments',
    '/comments',
    '/lpus',
    '/teams',
    '/settings',
  ],
  analista: [
    '/tasks',
    '/service-orders',
    '/collaborators',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/pdca',
    '/lpus',
    '/attachments',
    '/comments',
    '/settings',
  ],
  technician: [
    '/tasks',
    '/service-orders',
    '/stations',
    '/radio-links',
    '/projects',
    '/pdca',
    '/attachments',
    '/comments',
    '/settings',
  ],
  user: [
    '/tasks',
    '/service-orders',
    '/stations',
    '/radio-links',
    '/projects',
    '/clients',
    '/attachments',
    '/comments',
    '/settings',
  ],
  master: [],
}

export const DEFAULT_USER_MODULES = DEFAULT_ROLE_MODULES.user
